name: Require Checklist

on:
  pull_request:
    branches: [ "main" ]
    types: [ "ready_for_review", "synchronize" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
