name: Require Checklist

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ "main" ]
    types: [ "ready_for_review"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true
